openapi: 3.0.0
info:
  title: Echo API Gateway
  version: 1.0.0

paths:
  /auth/register:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ebf7s7a6utii7a9s3b
        tag: $latest
        service_account_id: aje792745pkupoc2scm7

  /auth/login:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ebf7s7a6utii7a9s3b
        tag: $latest
        service_account_id: aje792745pkupoc2scm7

  /posts:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ed73nh7d9r6sj606ma
        tag: $latest
        service_account_id: aje792745pkupoc2scm7

  /posts/create:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e5ah93pa4gbctuvmuq
        tag: $latest
        service_account_id: aje792745pkupoc2scm7

  /posts/{post_id}/edit:
    parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: string
    put:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4e2g8qod5mq21505pjp
        tag: $latest
        service_account_id: aje792745pkupoc2scm7

  /posts/{post_id}/delete:
    parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: string
    delete:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4edm18cmc672aanekjl
        tag: $latest
        service_account_id: aje792745pkupoc2scm7

  /posts/{post_id}/like:
    parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: string
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ern6kkanjnbhd0cp1r
        tag: $latest
        service_account_id: aje792745pkupoc2scm7

  /comments:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4elffqnr1rf3a9o8dn9
        tag: $latest
        service_account_id: aje792745pkupoc2scm7

  /health:
    get:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        http_headers:
          Content-Type: application/json
        content:
          status: ok
          service: echo-api

